storage:
  type: local
  path: data/evil
  create: true
grpc:
  port: 1999
swarm:
  keypair: CAESQAQZvXhMEgqFYgoxeykYCSdmLqwze3EXIVh4G89y4F9XLgKHrGPtiWvrErZSbX7eenguQobwJvZ/7GABNx4y55M
  leading_zeros: 2
  port: 8099
  bootstrap:
    - 127.0.0.1:8801
    - 127.0.0.1:8802
    - 127.0.0.1:8803
    - 127.0.0.1:8800
ledger:
  type: immudb
  username: immudb
  password: immudb
  address: 127.0.0.1:3322
malicious_behavior:
  type: none
verifier:
  enabled: false
por:
  enabled: true
