ledger:
  type: immudb
  username: immudb
  password: immudb
  address: 127.0.0.1:3322
grpc:
  port: 3030
keeper_gateway:
  addresses:
    - '[::1]:5005'
    - '[::1]:5006'
swarm:
  keypair: CAESQFTqF9JzGWIXLPwYdry8NTHwimUGV85kWTeBVgzk62jYhubG4byl61znGCAxSuGoHhPpOJrQ6u84fc89aQ2g4xU
  port: 2010
  bootstrap: []
