storage:
  type: local
  path: data/peer2
  create: true
grpc:
  port: 5004
swarm:
  keypair: CAESQFgI0esovILhf9w+v8TCeC4S6EAvW1t4EMEGysVr0xpBF97POcF7FGqiZE2R3pK5AKqUh9ataDS/OhihXKFHxCY
  port: 7070
  bootstrap:
    - 127.0.0.1:6060
